---
name: format
on:
  repository_dispatch:
    types: [format-command]
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Run format command
        run: |
          echo 'format command executed!'